version: "3"
services:
  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    container_name: es
    environment:
      - discovery.type=single-node
    expose:
      - 9200
  web:
    build: 
      context: web
      target: development
    command: python3 app.py
    environment:
      - DEBUG=True # set an env var for flask
    depends_on:
      - es
    ports:
      - 3000:3000
    volumes:
      - ./flask-app:/opt/flask-app
    restart: always
    networks:
      - web-flask
networks:
  web-flask:
